### ISSUE TITLE
Create Listings Functionality

### ISSUE THREAD

**Issue by PrateekSane** [VHomes-Group/VHomes_v2#41]
### Todo tasks for create listing component
**Overall form**
- [x] Redux
- [x] Save Data back and forth on certain components 
- [x] Record host's email to link account with listing
- [x] Add indication for optional fields

**Name**
- [x] Single input box (40 character cap) for listing name

**Address**
- [ ] Drop downs for country/state
- [ ] Check with account to make sure that listing hasn't been created already at the address

**Description**
- [x] Description box needs to change so that its one big block instead of one long line
- [x] Add 500 character limit to description

**Photos**
- [x] Photos

**Details**
- [x] Need limits on details page to make it so you cant select more than some amount

**Price**
- [x] Price box make it so that it gives more info like what cut VHomes will take and info like "per night"
- [x] Edit the input handler for price so that it shows a dollar sign by default e.g $____

**Rules**
- [ ] Make rules page expand to create a bullet point list instead of one string

**Dates**
- [x] Date picker should only select dates from current onward
- [x] Date picker should highlight the range of dates
- [x] Date picker should nicely show if its picking start/end and better display which dates are selected
- [x] Add a button to clear selection

**Confirmation**
- [x] Confirmation page clean data to show user

**Styling**
- [x] Price box prettify
- [ ] Confirmation page prettify
- [ ] Make all input pages same size so "next" button doesn't move around
