### ISSUE TITLE
Create MyReservations page under MyAccount

### ISSUE THREAD

**Issue by aidenszeto** [VHomes-Group/VHomes_v2#64]
## Backend
- [x] GET all reservations based on userId
- [x] GET all reservations based on listing id
- [x] GET one reservations based on reservation id
- [x] POST "checkout" button that deactivates reservation

**Comment by aidenszeto** [comment]
### Here's the information we want to display on the Reservation Cards:
- listing picture
- listing title
- listing location
- reservation dates
- reservation ID

The first three can be found in the listing object (the listingId associated with the reservation is in the reservation object), and the last two can be found in the reservation itself.


### Todo:
- [ ] Fix issue with MyReservations not clearing after switching tabs
- [ ] Copy the listingCard.component styling
- [ ] Add checkin/checkout buttons linked to ```/reservations/activate``` and ```/reservations/deactivate``` routes
